### PR TITLE
run_program: ensure safe failure when stack is small

### PR DESCRIPTION
**Pull request by sielicki**
In the case that only one element is present and a swap or combine is
attempted, an error will raise on the second pop(), and the contents of the
first pop() will be silently dropped. Rewrite these ops such that they attempt
to put contents back on the stack before returning an error.

Signed-off-by: Nicky Sielicki <sielicki@yandex.com>

### CODE REVIEW

**Comment by sielicki** [comment]
I really don't like that I had to clone in the cons fix. Maybe we can rewrite the `new_pair` signature from:

```fn new_pair( &mut self, first: Self::Ptr, rest: Self::Ptr,) -> Result<Self::Ptr, EvalErr<Self::Ptr>>```

To something like

```fn new_pair( &mut self, first: Self::Ptr, rest: Self::Ptr,) -> Result<Self::Ptr, EvalErr<(Self::Ptr, Self::Ptr)>>```

such that we get ownership of both parameters back in the case of an error.

**Comment by arvidn** [comment]
we have plans on dropping the `ArcAllocator`, which would simplify the ownerships of the Allocator trait. Then the `Ptr` type will implement `Copy` and be a primitive type.

Regarding this patch, could you add unit tests that exercise the problem you're solving?

**Comment by sielicki** [comment]
I would be very excited to see `ArcAllocator` be dropped -- my whole goal yesterday was to derive [Arbitrary](https://docs.rs/arbitrary/1.0.0/arbitrary/) on structures throughout the project so that I could implement `cargo fuzz` support, but I got lost in lifetime hell before I could make any substantial progress.

**Comment by arvidn** [comment]
the `ArcAllocator` has been removed now, and some owner relationships have been simplified. There are still things that can be simplified now, but I think this is enough to not have to clone node pointers (previously `Allocator::Ptr`, now called `NodePtr`).

**Comment by sielicki** [comment]
Closing due to losing context on what this was trying to accomplish in the first place. Sorry!

**Pull request closed without merging**
