### PR TITLE
clippy fixes

### PR DESCRIPTION
**Pull request by sielicki**
apologies for horrible pedantic drive-by nature of this PR, but it's really just fixing stuff that clippy complained about on nightly.

### CODE REVIEW

**Comment by arvidn** [comment]
This looks reasonable, but I think it would only make sense together with updating the github workflow to also use nightly clippy.

**Comment by sielicki** [comment]
Do you want me to do that, or do we like being on stable?

**Comment by arvidn** [comment]
I don't have a strong opinion. I take it "nightly" clippy is still reasonably stable in its checks. I just think the source code should stay in sync with CI.

@richardkiss what do you think?

**Comment by richardkiss** [comment]
This is fine and all, since eventually all these complains will come to stable rust, and these will be real errors. But what would make this PR really great would be a change that updates the clippy checks to use nightly rust so that new problems are created. What do you say @sielicki? (If you're not familiar with CI – "continuous integration" – start with the scripts in `.github`.)

**Comment by sielicki** [comment]
Sure -- I haven't worked with github actions specifically but I can give it a shot. 

Do you mean just rewriting the `check` [here](https://github.com/Chia-Network/clvm_rs/blob/main/.github/workflows/build-test.yml#L173-L189) to use the [clippy specific action from actions-rs](https://github.com/actions-rs/clippy-check)?

**Comment by richardkiss** [comment]
Sorry about the prior comment, I hadn't read the entire thread yet. These changes look good, thank you. I'll run the work-flow to make sure all tests still pass.

**Review by richardkiss — APPROVED** [review]

**Pull request merged**
