### PR TITLE
Disable nested cons eval

### PR DESCRIPTION
**Pull request by richardkiss**

### CODE REVIEW

**Comment by richardkiss** [comment]
A couple more tests in `clvm:develop` break without this change.

**Comment by richardkiss** [comment]
Oh shoot, it breaks the benchmarks. @arvidn I can help you with these later if you need it.

**Comment by richardkiss** [comment]
Basically, replace `((c PROG ARGS))` with `(a PROG ARGS)` and `(a ATOM ARGS)` with `(ATOM ARG1 ARG2 ...)` (quoting `ARGn` individually if necessary).

**Comment by richardkiss** [comment]
Probably easiest just to recompile everything.

**Review by arvidn — APPROVED** [review]

**Pull request merged**
