### PR TITLE
add the rust gitignore from github/gitignore

### PR DESCRIPTION
**Pull request by sielicki**

### CODE REVIEW

**Comment by sielicki** [comment]
if you're concerned about licensing, it came from here: https://raw.githubusercontent.com/github/gitignore/master/Rust.gitignore

https://github.com/github/gitignore/blob/master/LICENSE

**Review by arvidn — DISMISSED** [review]

**Comment by sielicki** [comment]
I just realized that this did not purge files which were checked in, but are now included in `.gitignore`. I just force pushed an amended commit which also purges Cargo.lock.

**Comment by richardkiss** [comment]
We've had problems deleting `Cargo.lock` in the past when a dependent library played loosie-goosie with its own dependencies, so I'm scared to merge. I don't remember the exact details now, and it's likely difficult to reproduce since a lot of the state is just "what's the most recent version of library X", which changes over time.

If we do delete `Cargo.lock` and the build breaks in the future, what's the strategy for fixing it?

**Comment by sielicki** [comment]
This PR is very simple to recreate so I'm going to close in the interim.

**Pull request closed without merging**
