### PR TITLE
`py.typed`

### PR DESCRIPTION
**Pull request by richardkiss**

### CODE REVIEW

**Comment by arvidn** [comment]
what does this do?
there's also a clippy warning: https://github.com/Chia-Network/clvm_rs/actions/runs/6674281647/job/18140915475?pr=343#step:4:337

**Comment by richardkiss** [comment]
Clippy warning is new. I guess `cargo-clippy` changed since the last release.

It's a tag that indicates to `mypy` that it should read the type hints and use them for linting.

**Comment by richardkiss** [comment]
I can fix the clippy recommendation separately.

**Comment by richardkiss** [comment]
https://github.com/Chia-Network/clvm_rs/pull/344 <-- clippy fix

**Review by arvidn — APPROVED** [review]

**Pull request merged**
