### PR TITLE
simplify run_program

### PR DESCRIPTION
**Pull request by arvidn**
by removing an op_stack entry that was only used once at start

### CODE REVIEW

**Comment by richardkiss** [comment]
Maybe consider just swapping the stack elements manually and using `swap_eval_op` rather than having special-purpose code above the loop? I'm fine either way though.

**Comment by arvidn** [comment]
I kind of like not having to create that extra pair too (just to match it again immediately following)

**Comment by arvidn** [comment]
I realized there was one more significant simplification that could be done. I added one more commit

**Review by richardkiss — APPROVED** [review]
Looks good.

**Pull request merged**
